### ISSUE TITLE
Category in Create Quiz step 2

### ISSUE THREAD

**Issue by satyarth934** [successar/Quizz#2]
http://127.0.0.1:8000/quizz/question/new/

After we give the name and the category of the quiz we are creating, shouldn't we have the category by default as well (like in the case of the quiz name)?

![screenshot from 2016-04-20 10 06 22](https://cloud.githubusercontent.com/assets/7209455/14663541/99e2060a-06df-11e6-8168-885ab99ec161.png)

**Comment by successar** [comment]
Yeah, we can do that. Generate a pull request once you implement it. I will merge it into the project.
